format = """$os$username$directory$git_branch$git_status$time$character"""

[os]
disabled = false
format = "[](#89898c)[ ](bg:#89898c fg:#090913)"

[username]
show_always = true
format = "[ $user ](bg:#89898c fg:#090913)[](fg:#89898c bg:#282850)"

[directory]
format = "[ $path ](bg:#282850 fg:#ffffff)"
truncation_length = 3

[git_branch]
symbol = ""
format = "[ $symbol $branch ](fg:#89898c bg:#282850)"

[git_status]
# 修复了这里的格式：去掉了多余的嵌套括号
format = "[$all_status$ahead_behind](fg:#89898c bg:#282850)"

[time]
disabled = false
format = "[  $time ](bg:#282850 fg:#ffffff)[ ](fg:#282850)"

[character]
success_symbol = '[❯](bold fg:#89898c)'
error_symbol = '[❯](bold fg:red)'
