background { monitor = ; path = /home/biyuan/Pictures/wallpapers/200b7c8972e020635c8013f7e2d402bebacc1885131ce2-KQB5ir.jpg; blur_passes = 3; blur_size = 8 }
input-field {
    size = 250, 50; outline_thickness = 2; dots_center = true
    outer_color = rgb(89898c); inner_color = rgb(090913); font_color = rgb(ffffff)
    position = 0, -100; halign = center; valign = center
}
label {
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M") </big></b>"
    color = rgb(ffffff); font_size = 64; position = 0, 100; halign = center; valign = center
}
