general {
    # 锁定屏幕的动作
    lock_cmd = pidof hyprlock || hyprlock
    
    # 核心保险：无论是自动休眠、还是你通过脚本/命令行触发休眠
    # 系统都会先执行这个锁定指令，确保你醒来时绝对是锁屏状态
    before_sleep_cmd = loginctl lock-session
    
    # 唤醒后的动作：点亮屏幕 (Niri 专属命令)
    after_sleep_cmd = niri msg action power-on-monitors
}

# 规则 1：5 分钟 (300秒) 闲置自动锁屏
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 规则 2：15 分钟 (900秒) 闲置自动物理休眠 (Hibernate)
listener {
    timeout = 900
    on-timeout = systemctl hibernate
}
