# 设置字体
  font_family      Adwaita Mono Nerd Font
  bold_font        auto
  italic_font      auto
  bold_italic_font auto

# 设置字体大小
  font_size 14

  #设置光标

  #设置光标形状
  curcursor_shape block
  text_fg_override_threshold 0

# 设置光标

  #未聚焦光标形状
  cursor_shape_unfocused block
  #未聚焦光标停止闪烁时间，0为永不闪烁
  cursor_stop_blinking_after 0

  #光标追踪动画,0为禁用，大于0的任何值将启用
  cursor_trail 1
  #设置启用光标路径的距离阈值
  cursor_trail_start_threshold 2
  #设置光标追踪的颜色
  cursor_trail_color none

# 背景设置
  foreground #dddddd
  background #000000
  #背景透明度,介于0至1之间
  background_opacity 0.6
  #背景模糊，正值启用
  background_blur 0
  #背景图片
  background_image none

# 窗口

  #隐藏标题栏
  hide_window_decorations yes
  window_padding_width 10

# 允许 Kitty 接收来自其它窗口的拖拽
# 默认通常是开启的，但你可以显式确认
copy_on_select yes
